name: Announcements workflow

on:
  release:
    types: [published]
  workflow_run:
    workflows: [AndroidMixMod workflow]
    types:
      - completed
  workflow_dispatch:

jobs:
  announce:
    if:  ${{ github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Get latest tag
        run: |
          echo "latest_tag=$(curl --silent https://api.github.com/repos/${{ github.repository }}/releases/latest | jq -r '.tag_name')" >> $GITHUB_ENV

      - name: Send telegram message on release
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            Новая версия: ${{ env.latest_tag }}
            
            https://github.com/${{ github.repository }}/releases/latest/
            
            #Download_APK
